### ISSUE TITLE
进入console时出错 输出如下    运行setup时提示 bundle: command not found

### ISSUE THREAD

**Issue by duanluoo** [yanyingwang/music_xiami2wangyi#1]
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/apple/Downloads/music_xiami2wangyi-master/bin/console:3:in `<main>'

**Comment by yanyingwang** [comment]
Please try this:  `gem install bundler`

**Comment by duanluoo** [comment]
thanks! It work now~
